export const BTenProducts = [
  [
    {
      name: 'Chicken burger',
      description: '100 gr chicken + tomato + cheese  Lettuce',
      price: 15,
      image: require('../assets/product_1.png'),
      count: 1,
    },
    {
      name: 'Cheese burger',
      description: '100 gr meat + onion + tomato + Lettuce cheese',
      price: 20,
      image: require('../assets/product_2.png'),
      count: 1,
    },
    {
      name: 'Роял бургер',
      description: 'Котлета говяжья, трюфельный мед, соус',
      price: 18,
      image: require('../assets/product_3.png'),
      count: 1,
    },
    {
      name: 'Сытый батя Бургер',
      description: '2 куриные котлеты, сыр тостерный, соленый огурец, соус ',
      price: 23,
      image: require('../assets/product_4.png'),
      count: 1,
    },
    {
      name: 'Бургер Big boss',
      description: 'куриная котлета, ветчина, соус горчичный, огурец',
      price: 30,
      image: require('../assets/product_5.png'),
      count: 1,
    },
    {
      name: 'Мексиканский бургер',
      description: 'куриная котлета, свежий огурец и помидор, кетчуп, соус',
      price: 36,
      image: require('../assets/product_6.png'),
      count: 1,
    },
    {
      name: 'Бургер Салмон',
      description: 'слабосоленый лосось, авокадо, огурец, помидор',
      price: 32,
      image: require('../assets/product_7.png'),
      count: 1,
    },
    {
      name: 'Бургер Беконатор',
      description: 'куриная котлета, бекон, свежий помидор, соус',
      price: 28,
      image: require('../assets/product_8.png'),
      count: 1,
    },
  ],
  [
    {
      name: 'Пицца Царская',
      description: 'салями, бекон, помидор, шампиньоны',
      price: 15,
      image: require('../assets/product_9.png'),
      count: 1,
    },
    {
      name: 'Пицца Палермо',
      description: 'ветчина, куриное филе, помидор, моцарелла',
      price: 18,
      image: require('../assets/product_10.png'),
      count: 1,
    },
    {
      name: 'Пицца Мясной бум',
      description: 'ветчина, охотничьи колбаски, бекон, маслины, петрушка',
      price: 16,
      image: require('../assets/product_11.png'),
      count: 1,
    },
    {
      name: 'Пицца Тоскано',
      description: 'ветчина, томат, перец болгарский, шампиньоны',
      price: 14,
      image: require('../assets/product_12.png'),
      count: 1,
    },
    {
      name: 'Пицца «4 Сыры»',
      description: 'пармезан, дорблю, моцарелла, гауда, сливочный соус',
      price: 15,
      image: require('../assets/product_13.png'),
      count: 1,
    },
    {
      name: 'Пицца Дижонская',
      description: 'бекон, охотничьи колбаски, соленый огурец, перец',
      price: 10,
      image: require('../assets/product_14.png'),
      count: 1,
    },
    {
      name: 'Пицца Кантри',
      description: 'салями, курица копченая, соленый огурец, помидор',
      price: 14,
      image: require('../assets/product_15.png'),
      count: 1,
    },
    {
      name: 'Пицца Прошуто',
      description: 'прошуто, моцарелла, фета, сливочный соус и руккола',
      price: 14,
      image: require('../assets/product_16.png'),
      count: 1,
    },
  ],
  [
    {
      name: 'Blue bubble ice',
      description: 'шарики тапиока с соком, лайм, мята, содовая, сироп',
      price: 10,
      image: require('../assets/product_17.png'),
      count: 1,
    },
    {
      name: 'Лимонад Вишня',
      description: 'Вишня, Мята, Сироп Вишня, Лед, Вода содовая',
      price: 11,
      image: require('../assets/product_18.png'),
      count: 1,
    },
    {
      name: 'Coca-Cola (0.33 л)',
      description: 'Безалкогольный сильногазированный напиток',
      price: 10,
      image: require('../assets/product_19.png'),
      count: 1,
    },
    {
      name: 'Американо 250мл',
      description: 'два сорта кофейных зерен — арабика и робуста',
      price: 12,
      image: require('../assets/product_20.png'),
      count: 1,
    },
    {
      name: 'Капучино XL',
      description: 'два сорта кофейных зерен — арабика и робуста',
      price: 13,
      image: require('../assets/product_21.png'),
      count: 1,
    },
    {
      name: 'Чай зеленый/черный',
      description: 'Чай Золотые типсы Цейлон сад Vithanakanda',
      price: 9,
      image: require('../assets/product_22.png'),
      count: 1,
    },
  ],
];

export const bTenAllProducts = BTenProducts.flat();
